name: local-environment
services:
  web:
    container_name: app
    build: .
    command: 'sh -c "uvicorn app.main:app --reload --host=0.0.0.0 --port=8001"'
#    command: 'sh -c "uvicorn app.main:app --reload --reload-dir /code --host 0.0.0.0 --port 8001"'
    ports:
      - '8001:8001'
    volumes:
      - .:/code
    networks:
      - db_network
    depends_on:
      - db
  db:
    container_name: db
    image: 'postgres:13.9-alpine'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: graphql_db
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - db_network
networks:
  db_network:
    driver: bridge
volumes:
  postgres_data:
